### ISSUE TITLE
docker-entrypoint.sh: cannot create /opt/flink/conf/flink-conf.yaml.tmp: Read-only file system

### ISSUE THREAD

**Issue by kinderyj** [GoogleCloudPlatform/flink-on-k8s-operator#213]
I deployed the flink-on-k8s-operator in my k8s cluster successfully, but when I created a cluster by 
kubectl apply -f flinkoperator_v1beta1_flinksessioncluster.yaml, there's some error logs in the docker-entrypoint.sh of taskmanager\jobmanager, see as below,

```
kubectl logs flinksessioncluster-sample-taskmanager-b7d7849f8-6z7zr --all-containers
Starting Task Manager
sed: couldn't open temporary file /opt/flink/conf/sedmzkeY2: Read-only file system
sed: couldn't open temporary file /opt/flink/conf/sedW8t3K3: Read-only file system
sed: couldn't open temporary file /opt/flink/conf/sededxmy3: Read-only file system
sed: couldn't open temporary file /opt/flink/conf/sedh7Y2L6: Read-only file system
/docker-entrypoint.sh: 126: /docker-entrypoint.sh: cannot create /opt/flink/conf/flink-conf.yaml.tmp: Read-only file system

```

```
kubectl logs flinksessioncluster-sample-jobmanager-64656cbb89-bnfhw
Starting Job Manager
sed: couldn't open temporary file /opt/flink/conf/sedOd2K7J: Read-only file system
sed: couldn't open temporary file /opt/flink/conf/sedCKKXFI: Read-only file system
sed: couldn't open temporary file /opt/flink/conf/sedi1j8NL: Read-only file system
/docker-entrypoint.sh: 88: /docker-entrypoint.sh: cannot create /opt/flink/conf/flink-conf.yaml.tmp: Read-only file system
```

As we know, the /opt/flink/conf/flink-conf.yaml is a configmap file, it can't be edited by the users, so it seems that the docker-entrypoint.sh is not compatible with the k8s?

**Comment by functicons** [comment]
The Flink docker-entrypoint.sh might try to edit flink-config.yaml with runtime values in some cases, when using the operator, we should avoid relying on these runtime values, instead declare them in the Flink properties of the FlinkCluster CR.

**Comment by functicons** [comment]
I'm thinking about making /opt/flink/conf/flink-conf.yaml editable, one solution could be: mount the configmap to another location (say /tmp/opt/flink/conf) first, then use an init container to copy it over to the /opt/flink/conf, then it becomes writable. But I'm not sure about the value of this change, is it necessary?

@elanv what do you think?

**Comment by elanv** [comment]
docker-entrypoint.sh in official Flink Docker image tries to update configurations related to connections between job managers and task managers. Basically all sed error is related to connection config updates and operator does it also. Therefore those errors don't affect actually.

note: https://github.com/apache/flink-docker/blob/master/1.10/scala_2.12-debian/docker-entrypoint.sh#L62-L130

But official image allows additional changes to flink-conf.yaml with environment variable FLINK_PROPERTIES. The entrypoint script doesn't seem to be good for k8s, but if users want to use it, we can provide mount option for config file as you said. @functicons  

Alternatively, we could make flink-docker use FLINK_CONF_DIR.

Flink upstream init script uses FLINK_CONF_DIR. 
https://github.com/apache/flink/blob/ab37867c474a9e5754e79045fa06c9ac145a3787/flink-dist/src/main/flink-bin/bin/config.sh#L315

But flink-docker doesn't use it.
https://github.com/apache/flink-docker/blob/master/1.10/scala_2.12-debian/docker-entrypoint.sh#L23

I think flink-docker should be fixed, otherwise use provided FLINK_CONF_DIR does not work. I'll try to make change it to flink-docker first.

**Comment by functicons** [comment]
Great, thanks!

**Comment by elanv** [comment]
Even if FLINK_CONF_DIR is enabled, JM/TM should have initcontainers to support this. But CRD doesn't have it now. @functicons What do you think add initcontainers to JM/TM?

**Comment by functicons** [comment]
I think it is okay to add a default init container to JM/TM.

**Comment by elanv** [comment]
The flink community seems to be discussing to improve the docker image overall. We need to watch the progress of the work first.

https://cwiki.apache.org/confluence/display/FLINK/FLIP-111%3A+Docker+image+unification?src=contextnavpagetreemode

**Comment by abuckenheimer** [comment]
@elanv do you have a suggested workaround for now? This issue seems to break starting a job session cluster with images later than 1.9

**Comment by elanv** [comment]
@abuckenheimer This issue does not seem to break Flink start because Flink configuration is provided by Kubernetes configMap. For Flink version 1.10 or above, I think the fail may be caused by new memory configuration constraint. If so, you can try a workaround described in https://github.com/GoogleCloudPlatform/flink-on-k8s-operator/issues/288#issuecomment-673810397

**Comment by abuckenheimer** [comment]
@elanv sorry I'm a flink newbie so I'm not entirely sure where this is breaking but my symptoms seem to match this issue more than the one your pointing to (not trying to set any `flinkProperties` at all). Following the instructions [here](https://github.com/GoogleCloudPlatform/flink-on-k8s-operator/blob/master/helm-chart/flink-operator/README.md) I set up the operator and then when I try to deploy a slightly modified(attached below) from [sample](https://github.com/GoogleCloudPlatform/flink-on-k8s-operator/blob/master/config/samples/flinkoperator_v1beta1_flinksessioncluster.yaml) `FlinkCluster` the task manager fails on startup. With the logs:

```
# kubectl logs flinksessioncluster-taskmanager-59fc4b4554-xssvr
Starting Task Manager
sed: couldn't open temporary file /opt/flink/conf/sed9XFLof: Read-only file system
sed: couldn't open temporary file /opt/flink/conf/sedEJRCaf: Read-only file system
sed: couldn't open temporary file /opt/flink/conf/sedVrYL7f: Read-only file system
/docker-entrypoint.sh: 72: /docker-entrypoint.sh: cannot create /opt/flink/conf/flink-conf.yaml: Read-only file system
/docker-entrypoint.sh: 120: /docker-entrypoint.sh: cannot create /opt/flink/conf/flink-conf.yaml.tmp: Read-only file system
[ERROR] The execution result is empty.
[ERROR] Could not get JVM parameters and dynamic configurations properly.
```

full `FlinkCluster` definition:
```
apiVersion: flinkoperator.k8s.io/v1beta1
kind: FlinkCluster
metadata:
  name: flinksessioncluster
spec:
  image:
    #  name: flink:1.8  <- works
    #  name: flink:1.9  <- works
    #  name: flink:1.10  <- fails
    name: flink:1.11  # <- fails
    pullPolicy: Always
  jobManager:
    accessScope: Cluster
    ports:
      ui: 8081
    resources:
      limits:
        memory: "1024Mi"
        cpu: "200m"
  taskManager:
    replicas: 1
    resources:
      limits:
        memory: "1024Mi"
        cpu: "200m"
    volumes:
      - name: cache-volume
        emptyDir: {}
    volumeMounts:
      - mountPath: /cache
        name: cache-volume
```

**Comment by elanv** [comment]
@abuckenheimer Logs related to sed don't really affect the execution. It seems that my explanation for the background of this problem was lacking. Flink operator automatically configures `{jobmanager,taskmanager}.heap.size` to the container's memory limit minus a certain margin so that the Flink process runs stably. The problem is caused by the feature of the Flink operator interfering with new Flink memory management feature. The message `Could not get JVM parameters and dynamic configurations properly.` indicates the problem.

So if you follow the workaround in comment #288, I think your issue will be resolved.

**Comment by dekel-malul-controlup** [comment]
Hey, I have a solution for the situation without messing with the dockerentrypoint.sh

goes as follow

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: flink-config
  labels:
    app: flink
data:
  flink-conf.yaml: |+
    high-availability: zookeeper
    high-availability.zookeeper.quorum: zookeeper:2181
    high-availability.zookeeper.path.root: /flink
    high-availability.storageDir: 
    kubernetes.cluster-id: "/default"
    restart-strategy: fixed-delay
    restart-strategy.fixed-delay.attempts: 10
    jobmanager.rpc.address: flink-jobmanager
    taskmanager.numberOfTaskSlots: 2
    blob.server.port: 6124
    jobmanager.rpc.port: 6123
    taskmanager.rpc.port: 6122
    queryable-state.proxy.ports: 6125
    jobmanager.memory.process.size: 1600m
    taskmanager.memory.process.size: 1728m
    parallelism.default: 2    

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: flink-config-properties
  labels:
    app: flink
data:
  log4j-console.properties: |+
    # This affects logging for both user code and Flink
    rootLogger.level = INFO
    rootLogger.appenderRef.console.ref = ConsoleAppender
    rootLogger.appenderRef.rolling.ref = RollingFileAppender

    # Uncomment this if you want to _only_ change Flink's logging
    #logger.flink.name = org.apache.flink
    #logger.flink.level = INFO

    # The following lines keep the log level of common libraries/connectors on
    # log level INFO. The root logger does not override this. You have to manually
    # change the log levels here.
    logger.akka.name = akka
    logger.akka.level = INFO
    logger.kafka.name= org.apache.kafka
    logger.kafka.level = INFO
    logger.hadoop.name = org.apache.hadoop
    logger.hadoop.level = INFO
    logger.zookeeper.name = org.apache.zookeeper
    logger.zookeeper.level = INFO

    # Log all infos to the console
    appender.console.name = ConsoleAppender
    appender.console.type = CONSOLE
    appender.console.layout.type = PatternLayout
    appender.console.layout.pattern = %d{yyyy-MM-dd HH:mm:ss,SSS} %-5p %-60c %x - %m%n

    # Log all infos in the given rolling file
    appender.rolling.name = RollingFileAppender
    appender.rolling.type = RollingFile
    appender.rolling.append = false
    appender.rolling.fileName = ${sys:log.file}
    appender.rolling.filePattern = ${sys:log.file}.%i
    appender.rolling.layout.type = PatternLayout
    appender.rolling.layout.pattern = %d{yyyy-MM-dd HH:mm:ss,SSS} %-5p %-60c %x - %m%n
    appender.rolling.policies.type = Policies
    appender.rolling.policies.size.type = SizeBasedTriggeringPolicy
    appender.rolling.policies.size.size=100MB
    appender.rolling.strategy.type = DefaultRolloverStrategy
    appender.rolling.strategy.max = 10

    # Suppress the irrelevant (wrong) warnings from the Netty channel handler
    logger.netty.name = org.apache.flink.shaded.akka.org.jboss.netty.channel.DefaultChannelPipeline
    logger.netty.level = OFF 
```    

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flink-jobmanager
spec:
  replicas: 2 # Set the value to greater than 1 to start standby JobManagers
  selector:
    matchLabels:
      app: flink
      component: jobmanager
  template:
    metadata:
      labels:
        app: flink
        component: jobmanager
    spec:
      imagePullSecrets:
      - name: cu-artifactory
      containers:
      - name: jobmanager
        image: artifactory.controlup.com/devops-docker-test/flink:1.13.0-scala_2.11-s3-presto
        imagePullPolicy: Always
        env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        # The following args overwrite the value of jobmanager.rpc.address configured in the configuration config map to POD_IP.
        args: ["jobmanager", "$(POD_IP)"]
        ports:
        - containerPort: 6123
          name: rpc
        - containerPort: 6124
          name: blob-server
        - containerPort: 8081
          name: webui
        livenessProbe:
          tcpSocket:
            port: 6123
          initialDelaySeconds: 30
          periodSeconds: 60
        volumeMounts:
        - name: flink-config-volume
          mountPath: /opt/flink/conf/flink-conf.yaml
          subPath: flink-conf.yaml
        - name: flink-config-properties
          mountPath: /opt/flink/conf/log4j-console.properties
          subPath: log4j-console.properties
        securityContext:
          runAsUser: 9999  # refers to user _flink_ from official flink image, change if necessary
      serviceAccountName: flink-service-account # Service account which has the permissions to create, edit, delete ConfigMaps
      volumes:
      - name: flink-config-volume
        configMap:
          name: flink-config
          defaultMode: 0777
      - name: flink-config-properties
        configMap:
          name: flink-config-properties
          defaultMode: 0777
```

**Comment by dekel-malul-controlup** [comment]
Hey, I have a solution for the situation without messing with the dockerentrypoint.sh

goes as follow

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: flink-config
  labels:
    app: flink
data:
  flink-conf.yaml: |+
    high-availability: zookeeper
    high-availability.zookeeper.quorum: zookeeper:2181
    high-availability.zookeeper.path.root: /flink
    high-availability.storageDir: s3://devops-flink/recovery
    kubernetes.cluster-id: "/default"
    restart-strategy: fixed-delay
    restart-strategy.fixed-delay.attempts: 10
    jobmanager.rpc.address: flink-jobmanager
    taskmanager.numberOfTaskSlots: 2
    blob.server.port: 6124
    jobmanager.rpc.port: 6123
    taskmanager.rpc.port: 6122
    queryable-state.proxy.ports: 6125
    jobmanager.memory.process.size: 1600m
    taskmanager.memory.process.size: 1728m
    parallelism.default: 2    

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: flink-config-properties
  labels:
    app: flink
data:
  log4j-console.properties: |+
    # This affects logging for both user code and Flink
    rootLogger.level = INFO
    rootLogger.appenderRef.console.ref = ConsoleAppender
    rootLogger.appenderRef.rolling.ref = RollingFileAppender

    # Uncomment this if you want to _only_ change Flink's logging
    #logger.flink.name = org.apache.flink
    #logger.flink.level = INFO

    # The following lines keep the log level of common libraries/connectors on
    # log level INFO. The root logger does not override this. You have to manually
    # change the log levels here.
    logger.akka.name = akka
    logger.akka.level = INFO
    logger.kafka.name= org.apache.kafka
    logger.kafka.level = INFO
    logger.hadoop.name = org.apache.hadoop
    logger.hadoop.level = INFO
    logger.zookeeper.name = org.apache.zookeeper
    logger.zookeeper.level = INFO

    # Log all infos to the console
    appender.console.name = ConsoleAppender
    appender.console.type = CONSOLE
    appender.console.layout.type = PatternLayout
    appender.console.layout.pattern = %d{yyyy-MM-dd HH:mm:ss,SSS} %-5p %-60c %x - %m%n

    # Log all infos in the given rolling file
    appender.rolling.name = RollingFileAppender
    appender.rolling.type = RollingFile
    appender.rolling.append = false
    appender.rolling.fileName = ${sys:log.file}
    appender.rolling.filePattern = ${sys:log.file}.%i
    appender.rolling.layout.type = PatternLayout
    appender.rolling.layout.pattern = %d{yyyy-MM-dd HH:mm:ss,SSS} %-5p %-60c %x - %m%n
    appender.rolling.policies.type = Policies
    appender.rolling.policies.size.type = SizeBasedTriggeringPolicy
    appender.rolling.policies.size.size=100MB
    appender.rolling.strategy.type = DefaultRolloverStrategy
    appender.rolling.strategy.max = 10

    # Suppress the irrelevant (wrong) warnings from the Netty channel handler
    logger.netty.name = org.apache.flink.shaded.akka.org.jboss.netty.channel.DefaultChannelPipeline
    logger.netty.level = OFF     
    ```
    
    ```
    apiVersion: apps/v1
kind: Deployment
metadata:
  name: flink-jobmanager
spec:
  replicas: 2 # Set the value to greater than 1 to start standby JobManagers
  selector:
    matchLabels:
      app: flink
      component: jobmanager
  template:
    metadata:
      labels:
        app: flink
        component: jobmanager
    spec:
      imagePullSecrets:
      - name: cu-artifactory
      containers:
      - name: jobmanager
        image: apache/flink
        imagePullPolicy: Always
        env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        # The following args overwrite the value of jobmanager.rpc.address configured in the configuration config map to POD_IP.
        args: ["jobmanager", "$(POD_IP)"]
        ports:
        - containerPort: 6123
          name: rpc
        - containerPort: 6124
          name: blob-server
        - containerPort: 8081
          name: webui
        livenessProbe:
          tcpSocket:
            port: 6123
          initialDelaySeconds: 30
          periodSeconds: 60
        volumeMounts:
        - name: flink-config-volume
          mountPath: /opt/flink/conf/flink-conf.yaml
          subPath: flink-conf.yaml
        - name: flink-config-properties
          mountPath: /opt/flink/conf/log4j-console.properties
          subPath: log4j-console.properties
        securityContext:
          runAsUser: 9999  # refers to user _flink_ from official flink image, change if necessary
      serviceAccountName: flink-service-account # Service account which has the permissions to create, edit, delete ConfigMaps
      volumes:
      - name: flink-config-volume
        configMap:
          name: flink-config
          defaultMode: 0777
      - name: flink-config-properties
        configMap:
          name: flink-config-properties
          defaultMode: 0777
```

**Comment by briannqc** [comment]
> I'm thinking about making /opt/flink/conf/flink-conf.yaml editable, one solution could be: mount the configmap to another location (say /tmp/flink-conf) first, then use an init container to copy it over to the /opt/flink/conf, then it becomes writable. But I'm not sure about the value of this change, is it necessary?
> 
> @elanv what do you think?

Hi @functicons I have a use case where I think making `conf/flink-conf.yaml` editable is necessary:

We are using a S3 compatible storage for Save/CheckPointStorage, so-called WOS (Whatever Object Storage). WOS doesn't support IAM but AccessKey and SecretKey only. If we put AK/SK in `Spec.FlinkProperties` like below, whoever can `kubectl describe flinkcluster` can steal AKSK very easily.

```yaml
spec:
    [...]
    flinkProperties:
        s3.access-key: "my-access-key"
        s3.secret-key: "my-secret-key"
```

Though, if we make `conf/flink-conf.yaml` editable, we can make use of environment variables and Secret to secure our AKSK, the official flink image already supports envsubst https://github.com/apache/flink-docker/blob/master/1.13/scala_2.12-java8-debian/docker-entrypoint.sh#L88

```yaml
spec:
    envFrom:
        - secretRef:
                name: flink-conf-secret
    flinkProperties:
        s3.access-key: ${S3_ACCESS_KEY}
        s3.secret-key: ${S3_SECRET_KEY}
```

Please kindly share with me your thoughts. Thanks
