### ISSUE TITLE
Does flinkjobcluster only accept long running jobs

### ISSUE THREAD

**Issue by Jeffwan** [GoogleCloudPlatform/flink-on-k8s-operator#216]
I rewrite streaming wordcount example to a batch wordcount example. 

```
apiVersion: flinkoperator.k8s.io/v1beta1
kind: FlinkCluster
metadata:
  name: flinkjobcluster-sample
spec:
  image:
    name: flink:1.8.2
  jobManager:
    ports:
      ui: 8081
    resources:
      limits:
        memory: "1024Mi"
        cpu: "200m"
  taskManager:
    replicas: 2
    resources:
      limits:
        memory: "1024Mi"
        cpu: "200m"
  job:
    jarFile: ./examples/batch/WordCount.jar
    className: org.apache.flink.examples.java.wordcount.WordCount
    args: ["--input", "./README.txt"]
    parallelism: 2
  flinkProperties:
    taskmanager.numberOfTaskSlots: "1"

```

Get error message here.
```
Checking existing jobs...
Waiting for response...
No running jobs.
No scheduled jobs.

Submitting job...
/opt/flink/bin/flink run --jobmanager flinkjobcluster-sample-jobmanager:8081 --class org.apache.flink.examples.java.wordcount.WordCount --parallelism 2 --detached ./examples/batch/WordCount.jar --input ./README.txt
Starting execution of program
Printing result to stdout. Use --output to specify output path.

------------------------------------------------------------
 The program finished with the following exception:

Job was submitted in detached mode. Results of job execution, such as accumulators, runtime, job id etc. are not available. Please make sure your program doesn't call an eager execution function [collect, print, printToErr, count].
	org.apache.flink.client.program.DetachedEnvironment$DetachedJobExecutionResult.getAccumulatorResult(DetachedEnvironment.java:108)
	org.apache.flink.api.java.DataSet.collect(DataSet.java:415)
	org.apache.flink.api.java.DataSet.print(DataSet.java:1652)
	org.apache.flink.examples.java.wordcount.WordCount.main(WordCount.java:88)

```

Seems controller submit job in detached mode. Seems this is different pattern from SessionCluster example and separate beam job. 

The problem of this pattern is if we want to have some short live workloads like wordcount, it can not have any eager execution functions. Trying to understand if `detach` mode is necessary here? 

As a workaround, I have to create a Session Cluster and then submit a Job.
