### ISSUE TITLE
Support the  Kubernetes secret value in flinkProperties

### ISSUE THREAD

**Issue by laughingman7743** [GoogleCloudPlatform/flink-on-k8s-operator#250]
I use Datadog for monitoring. I have set the flinkProperties as follows.
```yaml
flinkProperties:
  metrics.reporter.dghttp.class: org.apache.flink.metrics.datadog.DatadogHttpReporter
  metrics.reporter.dghttp.tags: tag1,tag2
  metrics.reporter.dghttp.apikey: xxx
```

In the current specification, the value of `metrics.reporter.dghttp.apikey` can only be specified as plain text. Isn't it possible to allow the Kubernetes secret value to be specified in the same way as envVars?
```yaml
flinkProperties:
  - name: metrics.reporter.dghttp.class
    value: org.apache.flink.metrics.datadog.DatadogHttpReporter
  - name: metrics.reporter.dghttp.tags
    value: tag1,tag2
  - name: metrics.reporter.dghttp.apikey
    valueFrom:
      secretKeyRef:
        name: datadog-secret
        key: api-key
```
```yaml
apiVersion: v1
kind: Secret
metadata:
  name: datadog-secret
  namespace: my-namespace
data:
  api-key: xxx
```
