### ISSUE TITLE
The sidecar container of JobManager does not start

### ISSUE THREAD

**Issue by laughingman7743** [GoogleCloudPlatform/flink-on-k8s-operator#251]
I'm trying to start a Datadog container as a sidecar container with the JobManager configuration shown below.

```yaml
  jobManager:
    ports:
      ui: 8081
    resources:
      requests:
        memory: "8192Mi"
        cpu: "500m"
      limits:
        memory: "8192Mi"
        cpu: "500m"
    volumes:
    - hostPath:
        path: /var/run/docker.sock
      name: dockersocket
    - hostPath:
        path: /proc
      name: procdir
    - hostPath:
        path: /sys/fs/cgroup
      name: cgroups
    sidecars:
    - image: datadog/agent:7
      imagePullPolicy: Always
      name: datadog-agent
      env:
      - name: DD_API_KEY
        valueFrom:
          secretKeyRef:
            name: datadog-secret
            key: api-key
      - name: DD_COLLECT_KUBERNETES_EVENTS
        value: "false"
      - name: DD_LEADER_ELECTION
        value: "false"
      - name: KUBERNETES
        value: "false"
      - name: DD_KUBERNETES_KUBELET_HOST
        valueFrom:
          fieldRef:
            fieldPath: status.hostIP
      - name: DD_APM_ENABLED
        value: "false"
      resources:
        requests:
          memory: "256Mi"
          cpu: "200m"
        limits:
          memory: "256Mi"
          cpu: "200m"
      volumeMounts:
      - name: dockersocket
        mountPath: /var/run/docker.sock
      - name: procdir
        mountPath: /host/proc
        readOnly: true
      - name: cgroups
        mountPath: /host/sys/fs/cgroup
        readOnly: true
```

The JobManager will start, but the sidecar container will not.
The sidecar container of TaskManager has been started with the following settings.

```yaml
  taskManager:
    replicas: 4
    resources:
      requests:
        memory: "8192Mi"
        cpu: "1000m"
      limits:
        memory: "8192Mi"
        cpu: "1000m"
    volumes:
    - hostPath:
        path: /var/run/docker.sock
      name: dockersocket
    - hostPath:
        path: /proc
      name: procdir
    - hostPath:
        path: /sys/fs/cgroup
      name: cgroups
    sidecars:
    - image: datadog/agent:7
      imagePullPolicy: Always
      name: datadog-agent
      env:
      - name: DD_API_KEY
        valueFrom:
          secretKeyRef:
            name: datadog-secret
            key: api-key
      - name: DD_COLLECT_KUBERNETES_EVENTS
        value: "false"
      - name: DD_LEADER_ELECTION
        value: "false"
      - name: KUBERNETES
        value: "false"
      - name: DD_KUBERNETES_KUBELET_HOST
        valueFrom:
          fieldRef:
            fieldPath: status.hostIP
      - name: DD_APM_ENABLED
        value: "false"
      resources:
        requests:
          memory: "256Mi"
          cpu: "200m"
        limits:
          memory: "256Mi"
          cpu: "200m"
      volumeMounts:
      - name: dockersocket
        mountPath: /var/run/docker.sock
      - name: procdir
        mountPath: /host/proc
        readOnly: true
      - name: cgroups
        mountPath: /host/sys/fs/cgroup
        readOnly: true
```

Is there something wrong with the settings?
