### ISSUE TITLE
How to enforce SSL/TLS everywhere through this operator?

### ISSUE THREAD

**Issue by a-roberts** [GoogleCloudPlatform/flink-on-k8s-operator#309]
Hey everyone, I've been trying this operator successfully on OpenShift after making a few small changes and applying a workaround https://github.com/GoogleCloudPlatform/flink-on-k8s-operator/issues/288 in to use Flink 1.11.

Now I'd like to check that I can use SSL/TLS everywhere as per https://ci.apache.org/projects/flink/flink-docs-stable/ops/security-ssl.html. I had a look through https://github.ibm.com/automation-base-pak/abp-flink-operator/blob/c017836993d94bf59c1082c9fbba300269c08e8e/docs/crd_v1alpha1.md and I noticed there's `useTLS` for the Ingress endpoint (I assume for external access, so perhaps securing the Flink UI?) but I don't see anything for internal communications.

Is it possible to achieve this through the operator and if so, how? I don't see it is as a supported feature on the main readme but I am thinking it would be done through an override in here for the FlinkCluster CR

```
spec:
  flinkProperties:
```

I'm wondering if anyone's done this before, I'll have a try anyway and see what happens, but couldn't find any documentation on this for the operator itself (lemme know if I've missed something please) and hence my curiosity in the event it's something not yet available.

Thanks!

**Comment by a-roberts** [comment]
Thanks @functicons, good to know! I'll be happy to share what myself and a colleague at IBM have at the moment, currently trying to submit a job to the Job Manager (by port-forwarding and doing a normal flink run) and seeing problems though, so while it may be secure* it's not so useful yet without good docs

* do you know of a good way to verify this?

**Comment by a-roberts** [comment]
@ SparkX120, a colleague at IBM, has suggested this would be an improvement to the CR instead of needing to specify all of the options as well, worth mentioning here I think:

```
FlinkCluster:
 metadata:
  name: my-cluster
 spec:
  ha:
   enabled: true
  tls:
   enabled: true
   existingTlsSecret: secret-name
  taskManager:
   replicas: 4
   memory: 4Gi
   taskSlots: 8
```

**Comment by chrispatmore** [comment]
Just in terms of simplicity. I find specifying something as enabled as
```yaml
tls: {}
```
rather than 
```yaml
tls:
  enabled: true
```
Is cleaner and easier to add. Then if someone wants access to additional configuration they open up the section. So
```yaml
  tls:
   existingTlsSecret: secret-name
   renewal:
   dnsNames:
   etc..
```
The same can be done with `ha`.

Additionally, when referencing a secret, there is a Kubernetes standard.
So
```yaml
tlsSecret:
  secretName: my-secret

or

tlsKey:
  secretName: my-secret
  key: tls.key
tlsCert:
  secretName: my-secret
  key: tls.crt
```
