### ISSUE TITLE
How to run JobManager and TaskManager pods as the flink user?

### ISSUE THREAD

**Issue by a-roberts** [GoogleCloudPlatform/flink-on-k8s-operator#312]
Hey everyone, I can specify a security context using the Job CR great, e.g.

```

apiVersion: batch/v1
kind: Job
metadata:
  name: sample-job
spec:
  template:
    spec:
      # Run as flink user
      securityContext:
        runAsUser: 9999
        runAsGroup: 9999
      containers:
```

how can I do this for the JobManager/TaskManager in our FlinkCluster CR please? I've tried it in this format (spec.template.spec), and just under spec (at the FlinkCluster level), and also by adding the securityContext under jobManager and taskManager under its definition in the FlinkCluster.

Thanks!
