### ISSUE TITLE
flink-job-cluster Helm variables for initContains are incomplete and azure specifc

### ISSUE THREAD

**Issue by KamalAman** [GoogleCloudPlatform/flink-on-k8s-operator#313]
There are a couple of issues with the initContainer in the flink-job-cluster Helm chart. 

First, command and args are not actually being passed into the FlinkCluster definition

`values.yaml` states
```yaml
  initContainers:
    enabled: false
#    image: <registry>/<container_name>
#    tag: "1.0"
#    command: ["/bin/sh","-c","--"]
#    args: ["/app/exec-python.sh"]
```

whereas the `flinkjobcluter.yaml` had command and args hard coded.
```yaml
   initContainers:
    - name: {{ .Chart.Name}}-python-blob-downloader
      image: "{{ .Values.job.initContainers.image }}:{{ .Values.job.initContainers.tag }}"
      command: ["/bin/sh","-c","--"]
      args: ["/app/exec-python.sh"]
```

Second, the env variables seem to be azure specific which assumes you're using azure Blob Storage.

```
      env: 
        - name: STORAGE_CONNECTION_STRING
          valueFrom:
            secretKeyRef:
              name: {{ .Values.job.initContainers.Storage.secretName }}
              key: {{ .Values.job.initContainers.Storage.secretNameKey }}
        - name: CONTAINER_NAME
          value: {{ .Values.job.initContainers.Storage.containerName }}
        - name: BLOB_NAME
          value: {{ .Values.job.initContainers.Storage.blobName }}
```
