### ISSUE TITLE
Connection refused applying FlinkCluster CR - yet pod is reported as ready and running

### ISSUE THREAD

**Issue by a-roberts** [GoogleCloudPlatform/flink-on-k8s-operator#315]
Hey all, we've been using the operator for a while and we've noticed some flakiness when applying the FlinkCluster CR. 
Specifically we see this, and we're wondering if perhaps it's due to the pod not actually being ready (and having the self-signed cert created and available in time).

```
base) Adams-MBP:abp-flink-operator aroberts$ k apply -f network-policy-cluster-flink-1.11.yaml networkpolicy.networking.k8s.io/network-job unchanged
networkpolicy.networking.k8s.io/network-policy-taskmanager unchanged
networkpolicy.networking.k8s.io/network-policy-jobmanager unchanged
Error from server (InternalError): error when creating "network-policy-cluster-flink-1.11.yaml": Internal error occurred: failed calling webhook "mflinkcluster.flinkoperator.k8s.io": Post https://flink-operator-webhook-service.abp.svc:443/mutate-flinkoperator-k8s-io-v1beta1-flinkcluster?timeout=30s: dial tcp 10.254.20.21:443: connect: connection refused

(base) Adams-MBP:abp-flink-operator aroberts$ k apply -f network-policy-cluster-flink-1.11.yaml networkpolicy.networking.k8s.io/network-job unchanged
networkpolicy.networking.k8s.io/network-policy-taskmanager unchanged
networkpolicy.networking.k8s.io/network-policy-jobmanager unchanged
Error from server (InternalError): error when creating "network-policy-cluster-flink-1.11.yaml": Internal error occurred: failed calling webhook "mflinkcluster.flinkoperator.k8s.io": Post https://flink-operator-webhook-service.abp.svc:443/mutate-flinkoperator-k8s-io-v1beta1-flinkcluster?timeout=30s: dial tcp 10.254.20.21:443: connect: connection refused

(base) Adams-MBP:abp-flink-operator aroberts$ k apply -f network-policy-cluster-flink-1.11.yaml networkpolicy.networking.k8s.io/network-job unchanged
networkpolicy.networking.k8s.io/network-policy-taskmanager unchanged
networkpolicy.networking.k8s.io/network-policy-jobmanager unchanged
Error from server (InternalError): error when creating "network-policy-cluster-flink-1.11.yaml": Internal error occurred: failed calling webhook "mflinkcluster.flinkoperator.k8s.io": Post https://flink-operator-webhook-service.abp.svc:443/mutate-flinkoperator-k8s-io-v1beta1-flinkcluster?timeout=30s: dial tcp 10.254.20.21:443: connect: connection refused
(base) Adams-MBP:abp-flink-operator aroberts$ k apply -f network-policy-cluster-flink-1.11.yaml  


networkpolicy.networking.k8s.io/network-job unchanged
networkpolicy.networking.k8s.io/network-policy-taskmanager unchanged
networkpolicy.networking.k8s.io/network-policy-jobmanager unchanged
Error from server (InternalError): error when creating "network-policy-cluster-flink-1.11.yaml": Internal error occurred: failed calling webhook "mflinkcluster.flinkoperator.k8s.io": Post https://flink-operator-webhook-service.abp.svc:443/mutate-flinkoperator-k8s-io-v1beta1-flinkcluster?timeout=30s: net/http: TLS handshake timeout
```

If we then wait a while (around a minute, and I actually did another make deploy at this stage):

```
(base) Adams-MBP:abp-flink-operator aroberts$ k apply -f network-policy-cluster-flink-1.11.yaml 
flinkcluster.flinkoperator.k8s.io/tls-flink-cluster-1-11 created
networkpolicy.networking.k8s.io/network-job unchanged
networkpolicy.networking.k8s.io/network-policy-taskmanager unchanged
networkpolicy.networking.k8s.io/network-policy-jobmanager unchanged
```

One idea would be to enhance the existing readiness mechanism we have - I'm wondering if anyone else has experienced this and what a solution may be.

Thanks!

@enriquel8

**Comment by a-roberts** [comment]
Have tried adding a readiness probe in Manager.yaml but still seeing this happening:

```
apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: controller-manager
  name: system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
  namespace: system
  labels:
    control-plane: controller-manager
    app: flink-operator
spec:
  selector:
    matchLabels:
      control-plane: controller-manager
      app: flink-operator
  replicas: 1
  template:
    metadata:
      labels:
        control-plane: controller-manager
        app: flink-operator
    spec:
      containers:
      - name: flink-operator
        readinessProbe:
          failureThreshold: 30
          httpGet:
            path: /mutate-flinkoperator-k8s-io-v1beta1-flinkcluster
            port: webhook-server
            scheme: HTTPS
          periodSeconds: 1
          successThreshold: 1
          timeoutSeconds: 30
        image: flink-operator:latest
        command:      
        - /flink-operator
        args:
        - --enable-leader-election
        resources:
          limits:
            cpu: 100m
            memory: 30Mi
          requests:
            cpu: 100m
            memory: 20Mi
      terminationGracePeriodSeconds: 10
```

still no good.

The MutatingWebhookConfiguration has:

```
      service:
        name: flink-operator-webhook-service
        namespace: abp
        path: /mutate-flinkoperator-k8s-io-v1beta1-flinkcluster
        port: 443
```

which is where my path comes from. The caBundle in there matches with what is in the webhook-server-cert secret.
