### ISSUE TITLE
How to set serviceAccount to pods by operator

### ISSUE THREAD

**Issue by yanghui16355** [GoogleCloudPlatform/flink-on-k8s-operator#329]
I am running my flink application in AWS EKS and need to set the serviceAccount(with AWS IAM role attached) to my flink pods. Based on current CRD, I don't see there is an option to pass the serviceAccount name to my flink pod. Can you point to me which option I can use to set serviceAccount or add this option if does't support yet. 

Thanks,

Hui

**Comment by functicons** [comment]
Currently, the CRD doesn't support specifying serviceAccount directly, it uses the `default` service account of the Flink cluster CR's namespace. A workaround is that you create/choose a custom namespace for your Flink application and grant necessary permissions to the `default` service account of the namespace:

```
apiVersion: flinkoperator.k8s.io/v1beta1
kind: FlinkCluster
metadata:
  name: flinkjobcluster-sample
  namespace: my-namespace
...
```

But I think it is a good FR to support custom serviceAccount for Flink JM/TM Pods. If you want to contribute the PR, I can review it.
