### ISSUE TITLE
x509: certificate relies on legacy Common Name field, use SANs or temporarily enable Common Name matching with GODEBUG=x509ignoreCN=0

### ISSUE THREAD

**Issue by nice1517** [GoogleCloudPlatform/flink-on-k8s-operator#390]
when i perform `kubectl apply -f config/samples/flinkoperator_v1beta1_flinksessioncluster.yaml`
An error is as follows:
`Error from server (InternalError): error when creating "config/samples/flinkoperator_v1beta1_flinksessioncluster.yaml": Internal error occurred: failed calling webhook "mflinkcluster.flinkoperator.k8s.io": Post "https://flink-operator-webhook-service.flink-operator-system.svc:443/mutate-flinkoperator-k8s-io-v1beta1-flinkcluster?timeout=30s": x509: certificate relies on legacy Common Name field, use SANs or temporarily enable Common Name matching with GODEBUG=x509ignoreCN=0
`

**Comment by nice1517** [comment]
Problems caused by version conflicts

I currently use k8S 1.19 version, this version of the Go voice is 1.15, so in fact there is a vulnerability, finally changed to K8S 1.18 after the normal operation

**Comment by schmichri** [comment]
Downgrading is not an option. Is there any progress in the >=1.18 support?

**Comment by schmichri** [comment]
a workround because of this bullshit is the following: Add your >=1.19 kube-api-server inside the file `/etc/kubernetes/manifests/kube-apiserver.yaml`  an Environment variable:

```
    name: kube-apiserver
# um dem scheiss flink-operator webhook zu supporten machen wir hier den workaround
    env:
    - name: GODEBUG
      value: "x509ignoreCN=0"

    readinessProbe:
```
