### ISSUE TITLE
savepointDir only supported  gs://?  we want to use s3://

### ISSUE THREAD

**Issue by kaohaonan6666** [GoogleCloudPlatform/flink-on-k8s-operator#395]
how to  use s3:// as our  savepointDir  how to solve the problem

**Comment by guanjieshen** [comment]
Also wondering if wasb:// would be supported as well?

**Comment by youngwookim** [comment]
@kaohaonan6666 You can write the savepoints into s3 bucket via ```s3a://``` prefix like following:
```
  job:
    jarFile: /opt/flink-job.jar
    savepointsDir: s3a://mybucketd/flink/savepoints
    autoSavepointSeconds: 360
 
(snip)

  flinkProperties:
    # for s3 access
    s3.access-key: "YOUR-ACCESS-KEY"
    s3.secret-key: "YOUR-SECRET-KEY

```
And also, you should make sure that your docker image contains the jars to access the s3 buckets. see https://github.com/GoogleCloudPlatform/flink-on-k8s-operator/blob/master/images/flink/docker/Dockerfile

I've revised ```Dockerfile``` to include jars in order to access aws s3, like following:
```
(snip)

# s3
ARG FLINK_S3_HADOOP_JAR_NAME=flink-s3-fs-hadoop-1.11.2.jar
ARG FLINK_S3_HADOOP_JAR_URI=https://repo1.maven.org/maven2/org/apache/flink/flink-s3-fs-hadoop/1.11.2/${FLINK_S3_HADOOP_JAR_NAME}

# s3
RUN echo "Downloading ${FLINK_S3_HADOOP_JAR_URI}" && \
  wget -q -O /opt/flink/lib/${FLINK_S3_HADOOP_JAR_NAME} ${FLINK_S3_HADOOP_JAR_URI}

```
Hope this helps.
