### ISSUE TITLE
create jobcluster failed

### ISSUE THREAD

**Issue by jiamo** [GoogleCloudPlatform/flink-on-k8s-operator#403]
kubectl apply -f config/samples/flinkoperator_v1beta1_flinkjobcluster.yaml

got such error

**Error from server (updating job is not allowed when spec.job.savepointsDir was not provided): error when applying patch:**

after add  spec.job.savepointsDir.

```
  job:
    jarFile: ./examples/streaming/WordCount.jar
    className: org.apache.flink.streaming.examples.wordcount.WordCount
    args: ["--input", "./README.txt"]
    parallelism: 2
    savepointsDir: gs://flink-save
```

the error don't change.
