### ISSUE TITLE
nodeSelector does not get picked up

### ISSUE THREAD

**Issue by sushraju** [GoogleCloudPlatform/flink-on-k8s-operator#483]
We are trying to set the `nodeSelector` attribute in the taskManagerConfig and jobManagerConfig, but, it gets ignored.  

```
jobManagerConfig:
    nodeSelector:
      k8s.mux.io/instancezone: primary
    resources:
      requests:
        memory: "1Gi"
        cpu: "500m"
      limits:
        memory: "1Gi"
    envConfig:
....
....
```

How do we get this to work?

**Comment by sushraju** [comment]
Here's the  crd:

```
jobManagerConfig:
              type: object
              properties:
                replicas:
                  type: integer
                  minimum: 1
                offHeapMemoryFraction:
                  type: number
                  minimum: 0
                  maximum: 1
                systemMemoryFraction:
                  type: number
                  minimum: 0
                  maximum: 1
                nodeSelector:
                  type: object
                  properties:
                    additionalProperties:
                      type: string
```

```
taskManagerConfig:
              type: object
              properties:
                taskSlots:
                  type: integer
                  minimum: 1
                offHeapMemoryFraction:
                  type: number
                  minimum: 0
                  maximum: 1
                systemMemoryFraction:
                  type: number
                  minimum: 0
                  maximum: 1
                nodeSelector:
                  type: object
                  properties:
                    additionalProperties:
                      type: string
```
